# Generated by Django 4.1.3 on 2022-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_foods_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
