# Generated by Django 4.1.3 on 2022-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_alter_news_type_newcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='NewComment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
