# Generated by Django 4.1.3 on 2022-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
