# Generated by Django 4.1.3 on 2022-12-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customer_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
