# Generated by Django 4.1.3 on 2022-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_job_of_type_team_type_of_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('num_person', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('request', models.TextField()),
            ],
        ),
    ]
